language: python
python:
  - 2.6
  - 2.7
# command to install dependencies
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script: python setup.py test
